# Generated by Django 2.1.1 on 2018-11-15 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UnitConversion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitconversion',
            old_name='title',
            new_name='convTitle',
        ),
    ]
